theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "net"
device = "enp37s0"
ip = true
speed_down = false
speed_up = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "weather"
format = "{temp}°"
service = { name = "openweathermap", api_key = "d8a7eb292448cdf4a76e9cd1c17cb853", city_id = "2947416", units = "metric" }

[[block]]
block = "time"
interval = 60
format = "%R %a %d/%m"
